# Generated by Django 2.1.7 on 2020-08-15 16:32

import apps.productos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.BigIntegerField(default=1, validators=[apps.productos.validators.precioMinimo]),
            preserve_default=False,
        ),
    ]
